### ISSUE TITLE
Software misses the point.

### ISSUE THREAD

**Issue by funbucks** [xtbit/notbitcoinxt#1]
"This version can be used to protect the status quo until real technical consensus is formed about the blocksize."

It's a miner supermajority that decides upon the blocksize, and an economic consensus necessary to uphold it, not a node like this.  

Technical consensus is unnecessary.

And no professional miner is going to run a software like this.

It would serve however to help XT appear to have increased node adoption, which may possibly influence miners and merchants to get on board.

In essence, this software defeats its own stated purpose.

**Comment by xtbit** [comment]
Miners can continue to keep the status quo consensus rules while tricking XT nodes into activating the fork when no supermajority actually exists. For the status quo it's business as usual, since they are not actually following XT consensus rules. The very threat of this is enough. Whether miners adopt this patch or patch their block templates themselves is irrelevant, the XT supporters can't be sure when supermajority actually exists.

On the other side, this patch also allows easy faking of XT node statistics. It cannot serve to help the XT cause when the node count cannot be relied upon. 

There is also the alternative https://github.com/basil00/PseudoNode run in `--stealth` mode.

**Comment by funbucks** [comment]
The 'very threat' of miners adopting a patch that could cause the value of the coins they mine to drop is negligible. Only hashpower which isn't concerned with an economic return would do this.

Spoofing nodes is all fine and well but the economics are against using hashpower to do anything other than try to earn bitcoins. 

Meddling with the node count at best.  Great work /s, pseudonode seems superior for that in all aspects.
